i = input('Digite algo:')
x = type(i)
print('O tipo primitivo é: {}'.format(x))
h = i.isnumeric()
print('Tem apenas numero? {}'.format(h))
g = i.isalpha()
print('Tem apenas letras? {}'.format(g))
l =i.isalnum()
print('É alphanuerico? {}'.format(l))
